MyBlog/MyBlog/Controllers/RegionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Models;
using MyBlog.Services;
using MyBlog.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBlog.Controllers
{   
    
    public class RegionsController : Controller
    {
        private IRegionsService _service { get; set; }

        public RegionsController(IRegionsService service)
        {
            _service = service;
        }

        public IActionResult Overview()
        {
            var regions = _service.GetAllRegions();
            return View(regions);
        }

        [HttpGet]
        [Authorize(Policy = "IsAdministrator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "IsAdministrator")]
        public IActionResult Create(Region region)
        {
            if (ModelState.IsValid)
            {
                _service.CreateRegion(region);
                return RedirectToAction("Overview");
            }

            return View(region);
        }
    }
}

MyBlog/MyBlog/Views/Regions/Create.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

@model MyBlog.Models.Region

@{ ViewBag.Title = "Add Region"; }

<form asp-controller="Regions" asp-action="Create" method="post">
    <div class="form-group">
        <label class="control-label" asp-for="Name">Name</label>
        <input type="text" asp-for="Name" class="form-control" required />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label" asp-for="Location">Location</label>
        <input type="text" asp-for="Location" class="form-control" required />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label" asp-for="PointsOfInterest">Points Of Interest</label>
        <input type="text" asp-for="PointsOfInterest" class="form-control" required />
        <span asp-validation-for="PointsOfInterest" class="text-danger"></span>
    </div><div class="form-group">
              <label class="control-label" asp-for="ExternalLink">External Link</label>
    <input type="text" asp-for="ExternalLink" class="form-control" required />
    <span asp-validation-for="ExternalLink" class="text-danger"></span>
</div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-warning" />
    </div>
</form>

MyBlog/MyBlog/Views/Regions/Overview.cshtml
@model List<MyBlog.Models.Region>

@{
    ViewBag.Title = "Regions";
}

<br />
<br />

    <a href="/Regions/Create" class="btn btn-secondary button">Add Region</a>

<br />
<br />

    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Location</th>
                <th scope="col">Points Of Interest</th>
                <th scope="col">External link</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var region in Model)
            {
                <tr>
                    <th scope="row">@region.Id</th>
                    <td>@region.Name</td>
                    <td>@region.Location</td>
                    <td>@region.PointsOfInterest</td>
                    <td><a href="@region.ExternalLink" class="btn btn-warning" target="_blank">More Info...</a></td>
                </tr>
            }
        </tbody>
    </table>